<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <base href="<?php $config = Zend_Registry::get('config'); echo $config->url->base;?>"/>
    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.8.17/jquery-ui.min.js"></script>
    <?php echo $this->headLink()
                    ->appendStylesheet("assets/css/style.css")
                    ->appendStylesheet("assets/css/libs/progress.css");
          echo $this->headScript()->appendFile("assets/js/libs/jquery.ui.touch-punch.min.js")
                                  ->appendFile("assets/js/libs/jquery.masonry.min.js")
                                  ->appendFile("assets/js/libs/expanding.js")
                                  ->appendFile("assets/js/libs/tiny_mce/tiny_mce.js")
                                  ->appendFile("assets/js/libs/bootstrap/js/bootstrap.min.js")
                                  ->appendFile("assets/js/libs/bootstrap/js/bootstrap-tooltip.js")
                                  ->appendFile("assets/js/libs/fileuploader.js")
                                  ->appendFile("assets/js/libs/jquery.event.drop.js");
    ?>
    <link href='http://fonts.googleapis.com/css?family=Muli|Open+Sans' rel='stylesheet' type='text/css'>

    <meta name="ROBOTS" content="ALL" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" href="Templates/Foody/images/apple-touch-icon.png" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="apple-touch-fullscreen" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=1024px" />

    <title>Foody</title>

    <!-- 	<base href="http://www.foody.co/dev/"></base> -->

    <!--
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-27949607-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
    -->

</head>

<body>

<!-- TOP TOOLBAR -->

<div id="topBar">
    <div class="innerWrap">
        <div class="inner">
            <div class="topBarBtn logo left"><a href="index"><div></div></a></div>
            <div title="New post" class="topBarBtn add left <?php echo ($this->selected === "post")?"selected": "";?>"><a href="post/add"><div></div><span>Post</span></a></div>
            <div title="User info" class="topBarBtn profile right"><a href="profile.html"><div></div><span>My Profile</span></a></div>
            <div class="searchFld right"><input type="text" placeholder="Search"><div></div></input></div>
            <div class="topBarBtn searchBtn right"><a><div></div></a></div>
        </div>
    </div>
</div>
<?php echo $this->layout()->content ?>
</body>
</html>
